tabWidth: 2
useTabs: false
quoteProps: consistent
singleQuote: true
trailingComma: all
proseWrap: always
overrides:
  - files: '*.parcelrc'
    options:
      parser: json
  - files: '*.svg'
    options:
      parser: html
